# Generated by Django 3.0.4 on 2020-04-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='工位名称', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='工位描述', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Voltage_value', models.FloatField()),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('Sound_value', models.FloatField()),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.Station')),
            ],
        ),
        migrations.CreateModel(
            name='PoolImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('Current_value', models.FloatField()),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.Station')),
            ],
        ),
    ]
