# Generated by Django 3.0.4 on 2020-04-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0002_auto_20200406_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='date_time',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='poolimg',
            name='date_time',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sound',
            name='date_time',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
