# Generated by Django 3.0.4 on 2020-04-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0003_auto_20200406_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolimg',
            name='value',
            field=models.TextField(),
        ),
    ]
